ACT/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Recruitment_System.urls')),
    path('company/', include('Company.urls')),
    path('user-admin/', include('UserAdmin.urls')),
    path('froala_editor/', include('froala_editor.urls')),

]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Recruitment_System/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.registration_view, name="signup"),
    path('job-list/', views.job_list, name='job-list'),
    path('job-sector/<slug:slug>', views.job_sector_categories, name='job_sector_categories'),
    path('job-detail/<slug:slug>', views.job_detail, name='Job-detail'),
    #User
    path('user-add-bookmark/<slug:slug>', views.user_add_bookmark, name="user-add-bookmark"),
    path('user-remove-bookmark/<slug:slug>', views.user_delete_bookmark, name='user-delete-bookmark'),
    path('user-apply-job/<slug:slug>', views.user_apply_job, name='user-apply-job'),
    path('user-cancel-job/<slug:slug>', views.user_cancel_job, name='user-cancel-job'),
    path('resetpassword/', views.reset_password, name='reset-password'),
    path('login/', views.login, name='login'),
    path('user-dashboard/', views.user_dashboard, name='user-dashboard'),
    path('user-profile/', views.user_profile, name='user-profile'),
    path('user-add-resume/', views.user_resume, name='user-resume'),
    path('user-add-education/', views.user_add_education, name='user-add-education'),
    path('user-education/<slug:slug>/',views.detail_user_education, name='detail-user-education'),
    path('user-delete-education/<slug:slug>',views.user_delete_education, name='user-delete-education'),
    path('user-add-experience/', views.user_add_experience, name='user-add-experience'),
    path('user-experience/<slug:slug>/',views.detail_user_experience, name='detail-user-experience'),
    path('user-delete-experience/<slug:slug>',views.user_delete_experience, name='user-delete-experience'),
    path('user-applied-job/', views.user_applied_jobs, name='user-applied-job'),
    path('user-bookmark/', views.user_bookmark, name='user-bookmark'),
    path('user-change-password/', views.user_change_password, name='user-change-password'),
    #Interviewer
    path('interviewer-dashboard/', views.interviewer_dashboard, name='interviewer-dashboard'),
    path('interviewer-info/', views.interviewer_personal_info, name='interviewer-personal-info'),
    path('interviewer-job-list/', views.interviewer_job_list, name='interviewer-job-list'),
    path('interviewer-job-detail/<slug:slug>', views.interviewer_job_detail, name='interviewer-job-detail'),
    path('interviewer-interviews-list/', views.interviewer_interviews_lists, name='interviewer-interviews-list'),
    path('interview-detail/<slug:slug>', views.interview_detail, name='interview_detail'),
    path('cancel-interview/<slug:slug>', views.interview_cancel, name='cancel-interview'),
    path('interview-scheduled/', views.interview_scheduled, name='interview-scheduled'),
    path('today-interviews/', views.interview_today_interview_list, name='today-interviews'),
    path('interview-now/<slug:slug>', views.interview_individual_now, name="interviews-now"),
    path('interview-job-status/', views.interview_candidate_job_status, name="interview-job-status"),
    path('interview-applicant-category/<slug:slug>', views.interview_applicant_category, name='interview_applicant_category')
]

Recruitment_System/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from froala_editor.fields import FroalaField
from Account.models import CustomUser
from django.utils.text import slugify
from unidecode import unidecode
import datetime
#Candidate
gender_list = [
    ('male', 'Male'),
    ('female', 'Female'),
]

class Candidate(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.SET_NULL, null=True)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    gender = models.CharField(max_length=10, choices=gender_list)
    date_of_birth = models.DateField()
    email = models.EmailField(max_length=40)
    phone1 = PhoneNumberField()
    phone2 = PhoneNumberField(blank = True)
    address = models.CharField(max_length=100)
    linked_in = models.URLField(blank=True, null=True)
    git_hub = models.URLField(blank=True, null=True)
    country = models.CharField(max_length=20)
    city = models.CharField(max_length=20)
    zip_code = models.CharField(max_length=10, blank=True, null=True)
    photo = models.ImageField(upload_to='Candidate/photo', null=True, blank=True)
    resume = models.FileField(upload_to='Candidate/Resume', null=True, blank=True)
    about = models.TextField()
    skill = models.ManyToManyField("Skill", blank=False) 
    slug = models.SlugField(unique=True, blank=True,  max_length=200)
    date_created = models.DateField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.first_name + " " + self.last_name
    
    def age(self):
        date = datetime.datetime.now()
        today = date.today()
        return today.year - self.date_of_birth.year - ((today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day))
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.user.username))
        super().save(*args, **kwargs)

education_status_list = [
    ('highschool', 'High School'),
    ('Certificate', 'Certificate'),
    ('diploma', 'Diploma'),
    ('bachelor-degree', "Bachelor's degree"),
    ('Master-degree', "Master's Degree"),
    ('doctorate', "Doctorate"),
    ('other', 'Other')
]

class Education(models.Model):
    candidate = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    institution_name = models.CharField(max_length=100)
    education_status = models.CharField(max_length=40, choices=education_status_list)
    field_of_study = models.CharField(max_length=40)
    education_period_start = models.DateField()
    education_period_end = models.DateField()
    slug = models.SlugField(unique=True, blank=True, max_length=200)

    def save(self, *args, **kwargs):
        if not self.slug:
            now = datetime.datetime.now()
            self.slug = slugify(unidecode(self.candidate.username)) + "-" + slugify(unidecode(self.institution_name)) + "-" + slugify(unidecode(self.field_of_study))
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.institution_name

class Experience(models.Model):
    candidate = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
    company_name = models.CharField(max_length=40)
    work_time_line_start =models.DateField()
    work_time_line_end = models.DateField()
    job_title = models.CharField(max_length=50)
    reference_phone = PhoneNumberField()
    reference_name = models.CharField(max_length=40)
    reference_email = models.CharField(max_length=40)
    reference_job_title = models.CharField(max_length=40)
    responsibility = models.TextField(null=True, blank=True)
    slug = models.SlugField(unique=True, blank=True,  max_length=200)

    def save(self, *args, **kwargs):
        if not self.slug:
            now = datetime.datetime.now()
            self.slug = slugify(unidecode(self.candidate.username)) +"-"+slugify(unidecode(self.company_name))
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.company_name

class Skill(models.Model):
    title = models.CharField(unique=True, max_length=30)
    slug = models.SlugField(unique=True, blank=True,  max_length=200)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.title))
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['title']
   
    def __str__(self) -> str:
        return self.title
    
class Bookmarks(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    job = models.ForeignKey('Job_Posting', on_delete=models.CASCADE)
    slug = models.SlugField(unique=True,blank=True,  max_length=200)

    def save(self, *args, **kwargs):
        if not self.slug:
            now = datetime.datetime.now()
            self.slug = slugify(unidecode(self.user.username)) + "-" + slugify(unidecode(self.job.title))+ '-' + now.strftime("%Y-%m-%d")
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.job.title


class Sector(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(unique=True, blank=True,  max_length=200)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.name))
        super().save(*args, **kwargs)

    def count_job_post(self) -> int:
        count = Job_Posting.objects.filter(sector_id = self.id).count()
        return count
    
    def count_interview_completed(self) -> int:
        applicant = Interviews.objects.filter(status='completed', application__job__sector_id = self.id).count()
        return applicant


    def __str__(self) -> str:
        return self.name


job_type = [
    ('full_time', 'Full Time'),
    ('part_time', 'Part Time'),
    ('freelance', 'Freelance'),
    ('internship', 'Internship'),
    ('seasonal ','seasonal'),
    ('contract', 'Contract'),
    ('remote', 'Remote'),
]


class Job_Posting(models.Model):
    title = models.CharField(max_length=50)
    sector = models.ForeignKey(Sector, on_delete=models.SET_NULL, null=True)  # Related With Sector
    description = FroalaField()
    vacancies = models.IntegerField()
    experience = models.CharField(max_length=20)
    skills = models.ManyToManyField(Skill)
    location = models.CharField(max_length=200)
    salary_range_start = models.FloatField()
    salary_range_final = models.FloatField()
    type = models.CharField( choices=job_type, max_length=30)
    job_status = models.BooleanField(default=False)
    date_posted = models.DateTimeField(auto_now_add=True)
    date_closed = models.DateField()
    slug = models.SlugField(unique=True,  max_length=200, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            now = datetime.datetime.now()
            self.slug = slugify(unidecode(self.title)) + '-' + now.strftime("%Y-%m-%d")
        super().save(*args, **kwargs)
  
    class Meta:
        ordering = ['-date_posted','-date_closed']

    def count_applicant(self) -> int:
        applicant = Application.objects.filter(job__id = self.id).count()
        return applicant
    
    def count_interview_pending(self) -> int:
        applicant = Application.objects.filter(status='pending', job__id = self.id).count()
        return applicant
    
    def count_interview_completed(self) -> int:
        applicant = Interviews.objects.filter(status='completed', application__job__id = self.id).count()
        return applicant

    def __str__(self) -> str:
        return self.title

application_status = [
    ('pending', 'Pending'),
    ('in_review', 'In review'),
    ('rejected', 'Rejected'),
    ('hired', 'Hired')
]

class Application(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)  # Related with Candidate
    job = models.ForeignKey(Job_Posting, on_delete=models.SET_NULL, null=True)  # Related with Job_Post
    date_applied = models.DateField(auto_now_add=True) # Select Option from application_status
    status = models.CharField(max_length=15, choices=application_status, default='pending')
    slug = models.SlugField(unique=True, null=True, blank=True, max_length=200)

    def save(self, *args, **kwargs):
        if not self.slug:
            now = datetime.datetime.now()
            self.slug = slugify(unidecode(self.user.username)) + '-' + slugify(unidecode(self.job.title)) + '-' + now.strftime("%Y-%m-%d")
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return str(self.user.username)+" - "+str(self.job)
    
    class Meta:
       ordering = ['-date_applied']

interview_status = [
    ('pending', 'Pending'),
    ('scheduled', 'Scheduled'),
    ('completed', 'Completed'),
    ('canceled', 'Canceled'),
]

job_status_interview = [
    ('pending', 'Pending'),
    ('rejected', 'Rejected'),
    ('hired', 'hired'),
]

interview_type = [
    ('phone', 'Phone'),
    ('in-person', 'In-Person'),
    ('video', 'Video')
]

class Interviews(models.Model):
    application = models.ForeignKey(Application, on_delete=models.CASCADE, null=True, blank=True)
    interviewer = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)  # Related with User
    date_schedule = models.DateField(null=True, blank=True)
    time_schedule = models.TimeField(null=True, blank=True)
    status = models.CharField(max_length=15, choices=interview_status, default='pending', null=True, blank=True)
    type = models.CharField(max_length=15, choices=interview_type, null=True, blank=True)
    note = FroalaField( null=True, blank=True)
    slug = models.SlugField(unique=True, null=True, blank=True, max_length=600)

    def save(self, *args, **kwargs):
        if not self.slug:
            now = datetime.datetime.now()

Recruitment_System/templates/RMS/Interviewer/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8" />
	<meta name="author" content="Themezhub" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Workplex - Creative Job Board HTML Template</title>
	<link href="{% static 'assets/css/styles.css' %}" rel="stylesheet" />
	{% include 'include/head.html' %}
</head>

<body>
	<div id="main-wrapper">
		<div class="dashboard-wrap bg-light">
					 <!--Left Navbar-->
		  {% include 'RMS/interviewer/include/navbar.html'%}
			<div class="dashboard-content">
				<div class="dashboard-tlbar d-block mb-5">
					<div class="row">
						<div class="colxl-12 col-lg-12 col-md-12">
							<h1 class="ft-medium">Hello, {{user.first_name|capfirst}} {{user.last_name|capfirst}}</h1>
							<nav aria-label="breadcrumb">
								<ol class="breadcrumb">
									<li class="breadcrumb-item text-muted"><a href="#">Home</a></li>
									<li class="breadcrumb-item"><a href="#" class="theme-cl">Dashboard</a></li>
								</ol>
							</nav>
						</div>
					</div>
				</div>

				<div class="dashboard-widg-bar d-block">
					<div class="row">
						<div class="col-xl-4 col-lg-4 col-md-6 col-sm-6">
							<div class="dash-widgets py-5 px-4 bg-success rounded">
								<h2 class="ft-medium mb-1 fs-xl text-light">{{total_jobs}}</h2>
								<p class="p-0 m-0 text-light fs-md">Total Jobs</p>
								<i class="lni lni-empty-file"></i>
							</div>
						</div>
						<div class="col-xl-4 col-lg-4 col-md-6 col-sm-6">
							<div class="dash-widgets py-5 px-4 bg-purple rounded">
								<h2 class="ft-medium mb-1 fs-xl text-light">{{total_application}}</h2>
								<p class="p-0 m-0 text-light fs-md">Total Applications</p>
								<i class="lni lni-users"></i>
							</div>
						</div>
						<div class="col-xl-4 col-lg-4 col-md-6 col-sm-6">
							<div class="dash-widgets py-5 px-4 bg-danger rounded">
								<h2 class="ft-medium mb-1 fs-xl text-light">{{total_interview}}</h2>
								<p class="p-0 m-0 text-light fs-md">Total Interviews</p>
								<i class="lni lni-bar-chart"></i>
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-lg-6 col-md-12">
							<div class="dashboard-gravity-list with-icons">
								<h4 class="mb-0 ft-medium">Today Interviews</h4>
								<ul>
									{% for interview in today_interviews%}
									<li>
										<i class="dash-icon-box ti-layers text-purple bg-light-purple"></i>
										 {{interview.application.user.first_name}} {{interview.application.user.last_name}}
										 scheduled for
										<strong class="ft-medium text-dark"><a href="#"> {{interview.application.job.title}}</a></strong> 
										at {{interview.time_schedule | time | upper}}
										<a href="#" class="close-list-item"><i class="fas fa-times"></i></a>
									</li>

									{% endfor %}
								</ul>
							</div>
						</div>

						<div class="col-lg-6 col-md-12">
							<div class="dashboard-gravity-list invoices with-icons">
								<h4 class="mb-0 ft-medium">Recent Applicant Status</h4>
								<ul>

									{% for applicant in applicant_status%}
									<li><i class="fa-regular fa-user text-warning bg-light-warning ps-0"></i>
										<strong class="ft-medium text-dark">{{applicant.application.user.candidate.first_name | capfirst}}  {{applicant.application.user.candidate.last_name | capfirst}}</strong>
										<ul>
											<li class="unpaid">Interview: {{applicant.get_status_display}}</li>
											<li>Job Status: {{applicant.application.get_status_display}}</li>
											<li>Applied Date: {{applicant.application.date_applied}}</li>
										</ul>
									</li>
									{% endfor %}

								</ul>
							</div>
						</div>
					</div>

				</div>

				<!-- footer -->
				<div class="row">
					<div class="col-md-12">
						<div class="py-3">© 2023 Workplex. Designd By ThemezHub.</div>
					</div>
				</div>

			</div>

		</div>
		<!-- ======================= dashboard Detail End ======================== -->

		<a id="back2Top" class="top-scroll" title="Back to top" href="#"><i class="ti-arrow-up"></i></a>


	</div>
	<!-- ============================================================== -->
	<!-- End Wrapper -->
	<!-- ============================================================== -->

	<!-- ============================================================== -->
	<!-- All Jquery -->
	<!-- ============================================================== -->
	<script src="assets/js/jquery.min.js"></script>
	<script src="assets/js/popper.min.js"></script>
	<script src="assets/js/bootstrap.min.js"></script>
	<script src="assets/js/slick.js"></script>
	<script src="assets/js/slider-bg.js"></script>
	<script src="assets/js/smoothproducts.js"></script>
	<script src="assets/js/snackbar.min.js"></script>
	<script src="assets/js/jQuery.style.switcher.js"></script>
	<script src="assets/js/custom.js"></script>
	<!-- ============================================================== -->
	<!-- This page plugins -->
	<!-- ============================================================== -->

</body>

<!-- Mirrored from themezhub.net/workplex-demo/workplex/employer-dashboard.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 08 Jul 2023 02:13:52 GMT -->

</html>

Recruitment_System/templates/RMS/Interviewer/interview-scheduled.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="author" content="Themezhub" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>JOB-Lists | ACT - American College Of Technology </title>
    <link href="{% static 'assets/css/styles.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.5/css/jquery.dataTables.min.css" />
    {% include 'include/head.html' %}

  </head>

  <body>
    <div id="main-wrapper">
      <div class="dashboard-wrap bg-light">
		 <!--Left Navbar-->
		{% include 'RMS/interviewer/include/navbar.html'%}
        <div class="dashboard-content">
          <div class="dashboard-tlbar d-block mb-5">
            <div class="row">
              <div class="colxl-12 col-lg-12 col-md-12">
                <h1 class="ft-medium">JOB Lists</h1>
              </div>
            </div>

            {% include 'RMS/messages.html'%}
          
          </div>

          <div class="dashboard-widg-bar d-block mb-5">
            <div class="row">

              <div class="col-xl-12 col-lg-12 col-md-12">
                <div class="mb-4 tbl-lg rounded overflow-hidden">
                  <div class="table-responsive bg-white">
                    <table class="table">
                      <thead class="thead-dark">
                        <tr>
                          <th scope="col">Full Name</th>
                          <th scope="col">Job Title</th>
                          <th scope="col">Applied Date</th>
                          <th scope="col">Interviews Dste</th>
                          <th scope="col">Job Status</th>
                          <th scope="col">Action</th>
                        </tr>
                      </thead>
                      <tbody>
                        <table id="example" class="display " style="width:100%">
                          <thead>
                              <tr>
                                  <th>Full Name</th>
                                  <th>Job Title</th>
                                  <th>Applied Date</th>
                                  <th>Interviews Date</th>
                                  <th>Job Status</th>
                                  <th>Action</th>
                              </tr>
                          </thead>
                          <tbody class="bg-white">
                            {% for interview in interviews %}
                            <tr class="bg-white">
                              <td class="bg-white">
                                <div class="cats-box rounded d-flex align-items-center">
                                  <div class="text-center">
                                    
                                  </div>
                                  <div class="cats-box-caption px-2">
                                    <h4 class="fs-md mb-0 ft-medium">
                                      {{interview.application.user.candidate.first_name}} {{interview.application.user.candidate.last_name}}
                                    </h4>
                                    <div class="d-block mb-2 position-relative">
                                      <span class="muted medium ms-2 theme-cl"><i class="lni lni-briefcase me-1"></i>{{job.job.get_type_display}}</span>
                                    </div>
                                  </div>
                                </div>
                              </td>
                              <td>
                                <span>{{interview.application.job.title}}</span>
                              </td>
                              <td>
                                <span>{{ interview.application.date_applied | date }}</span>
                              </td>
                              <td>
                                <span>{{ interview.date_schedule | date }} at {{ interview.time_schedule | time }} </span> 
                              </td>
                              <td>
                                <span>{{ interview.application.get_status_display}}</span>
                              </td>
                              <td>
                                <div class="dash-action">
                                  {% if request.path == '/interview-scheduled/' %}
                                  <a
                                    href=" {% url 'interview_detail' interview.slug %} "
                                    class="p-2 circle text-info bg-light-info d-inline-flex align-items-center justify-content-center me-1"
                                    ><i class="lni lni-eye"></i>
                                  </a>
                                  {% else %}
                                  <a
                                  href="{% url 'interviews-now' interview.slug %}"
                                  class="btn {% if interview.status == 'completed'%} btn-success {% else %}btn-primary {% endif %} ">
                                  {% if interview.status == 'completed'%}
                                  Completed
                                  {% else %}
                                  Interview Now
                                  {% endif %}
                                  </a>
                                  {% endif %}

                                </div>
                              </td>
                            </tr>
                            {% endfor %}
                             
                          </tbody>
                      </table>

                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>


          </div>
        </div>
      </div>
      <!-- ======================= dashboard Detail End ======================== -->

      <a id="back2Top" class="top-scroll" title="Back to top" href="#"
        ><i class="ti-arrow-up"></i
      ></a>
    </div>
    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <script src="https://cdn.datatables.net/1.13.5/js/jquery.dataTables.min.js"></script>
    <script>
      new DataTable('#example');
    </script>
    {% include 'include/footerjs.html' %} 
  </body>
</html>

Recruitment_System/templates/RMS/Interviewer/personal-info.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="author" content="Themezhub" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>User Resume | ACT - American College Of Technology</title>
    <link href="{% static 'assets/css/styles.css' %}" rel="stylesheet" />
    {% include 'include/head.html' %}
  </head>

  <body>
    <div class="dashboard-wrap bg-light">
      <!--Left Navbar-->
      {% include 'RMS/Interviewer/include/navbar.html'%}

      <div class="dashboard-content">
        <div class="dashboard-tlbar d-block mb-5">
          <div class="row">
            <div class="colxl-12 col-lg-12 col-md-12">
              <!-- Start home -->
              <section class="page-title-box" style="height: 0px">
                <div class="container">
                  <div class="row justify-content-center">
                    <div class="col-md-6">
                      <div class="text-center text-white">
                        <h3 class="mb-4">Resume</h3>
                        <div class="page-next">
                          <nav
                            class="d-inline-block"
                            aria-label="breadcrumb text-center"
                          >
                            <ol class="breadcrumb justify-content-center">
                              <li class="breadcrumb-item">
                                <a href="{% url 'index' %}">Home</a>
                              </li>
                              <li class="breadcrumb-item">
                                <a href="javascript:void(0)">Dashboard</a>
                              </li>
                              <li
                                class="breadcrumb-item active"
                                aria-current="page"
                              >
                                Edit Resume
                              </li>
                            </ol>
                          </nav>
                        </div>
                      </div>
                    </div>
                    <!--end col-->
                  </div>
                  <!--end row-->
                </div>
                <!--end container-->
              </section>
              <!-- end home -->
            </div>
          </div>
        </div>

        <div class="dashboard-widg-bar d-block">
          <div class="row">
            <div class="col-xl-12 col-lg-12 col-md-12">
              <div class="_dashboard_content bg-white rounded mb-4">
                <div class="_dashboard_content_header br-bottom py-3 px-3">
                  <div class="_dashboard__header_flex">
                    <h4 class="mb-0 ft-medium fs-md">
                      <i class="fa fa-file me-1 theme-cl fs-sm"></i>Create
                      Resume
                    </h4>
                  </div>
                </div>

                <div class="_dashboard_content_body py-3 px-3">
                  {% include 'RMS/messages.html' %}
                  <form class="row d-flex justify-content-center " method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="col-xl-10 col-lg-10col-md-12 col-sm-12 ">
                     <div class="row ">
                      <div class="col-xl-12 col-lg-12 mb-2">
                        <label for="id_photo">Upload Profile Picture less than 1 MB {% for err in form.photo.errors %} <small class="text-danger"> {{err}} </small> {% endfor %}</label>
                        
                      {% if user.photo%}
                        <br>
                        <img src="/media/{{user.photo}}" class="img-fluid mx-auto d-block avatar-lg img-thumbnail rounded-circle mb-4" style="width: 200px; height: 200px;" alt="">
                        <br>
                       {% endif %}
                        {{form.photo}}
                      </div>
                     </div>
                      <div class="row mt-2 ">
                        <!--First Name-->
                        <div class="col-xl-6 col-lg-6">
                          <div class="form-group">
                            <label
                              class="text-dark ft-medium"
                              for="id_first_name"
                              >*First Name {% for err in form.first_name.errors %} <small class="text-danger"> {{err}} </small> {% endfor %} </label
                            >
                            {{form.first_name}}
                          </div>
                        </div>

                        <!--Last Name-->
                        <div class="col-xl-6 col-lg-6">
                          <div class="form-group">
                            <label
                              class="text-dark ft-medium"
                              for="id_last_name"
                              >*Last Name {% for err in form.last_name.errors %} <small class="text-danger"> {{err}} </small> {% endfor %}</label
                            >
                            {{form.last_name}}
                          </div>
                        </div>

                        <!--Email-->
                        <div class="col-xl-12 col-lg-12">
                          <div class="form-group">
                            <label class="text-dark ft-medium" for="id_email"
                              >*Email {% for err in form.email.errors %} <small class="text-danger"> {{err}} </small> {% endfor %}</label
                            >
                            {{form.email}}
                          </div>
                        </div>

                                      <!-- Save -->
                  <div class="row mb-5">
                    <div class="col-lg-12 col-md-12">
                      <button
                        type="submit"
                        class="btn btn-md ft-medium text-light rounded theme-bg"
                      >
                        Save
                      </button>
                    </div>
                  </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>